on:
  pull_request:
    types:
      - opened

jobs:
  terraform:
    name: Terraform
    environment:
      name: DEV
    env:
      create: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Create Terraform Plan Artifact for Apply'
      run: |
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -backend-config="bucket=${{ secrets.BUCKET }}" \
          -backend-config="key=${{ secrets.KEY }}" \
          -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE }}" \
          -backend-config="region=${{ secrets.AWS_REGION }}"
        terraform force-unlock -force bea1883b-b3c7-e3d6-9869-f590d0269d7d
